### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by hackthepentagon** [strong-code/pirata#8]
Use the gem as part of an iOS app, currently not working

Think it might have something to do with BASE_URL bring out of date

**Comment by hackthepentagon** [comment]
Doesn't support new https

update BASE_URL in config to this: BASE_URL = "http://proxy.dfiance.net"

**Comment by strong-code** [comment]
Hi @hackthepentagon 

Looks like you're right - that domain appears dead. Additionally, the host I was using for finding proxies also died. I've updated the BASE_URL and the comment for proxy lists. Tests are passing locally so I'll push the changes to master and re-release the gem.

fyi thew update BASE_URL is now using https, but it may be a good idea to let the user decide if they want to use HTTPS or regular HTTP.
